"""Add soft delete to all tables

Revision ID: 7e76f8690a44
Revises: 8ac25da42150
Create Date: 2024-08-06 22:56:04.417200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e76f8690a44'
down_revision = '8ac25da42150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accesorio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('caracteristica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('fabricante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('marca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('marca', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('fabricante', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('caracteristica', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('accesorio', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
